apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: access-monitor-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: access-monitor-front-service
          servicePort: 8080