apiVersion: apps/v1 
kind: Deployment
metadata:
  name: access-monitor-database-deployment
spec:
  selector:
    matchLabels:
      app: access-monitor
  replicas: 1 
  template:
    metadata:
      labels:
        app: access-monitor
    spec:
      containers:
      - name: database
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: "/data/db"
          name: mongo-volume
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-claim0

